// <auto-generated />
namespace MvcApplication3.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemovePrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovePrice));
        
        string IMigrationMetadata.Id
        {
            get { return "201303100002339_RemovePrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
